compilation : test.c
	gcc -c test.c -o test.o 

EDL : test.o
	gcc test.o -o test

compListeSimple: listeSimple.c
	gcc -c listeSimple.c -o listeSimple.o

EDLlisteSimple: listeSimple.c 
	gcc listeSimple.o -o listeSimple

compArgument: arguments.c
	gcc -c arguments.c -o arguments.o

EDLArgument: arguments.o
	gcc arguments.o -o arguments

AllArgument: arguments.c
	gcc arguments.c -o arguments

comptaille: taille.c
	gcc -c taille.c -o taille.o

EDLtaille: taille.o
	gcc taille.o -o taille

Alltaille: taille.c
	gcc taille.c -o taille