
path=/users/dut/info/Public/Systeme/stillOnTheRoad


compstillOnTheRoad:
	gcc -c -I$(path) stillOnTheRoad.c -o stillOnTheRoad.o 

EDLstillOnTheRoad:
	gcc  stillOnTheRoad.o  -o stillOnTheRoad -L$(path) -pthread -lroad -lallegro -lallegro_primitives 


compstillOnTheRoadQ2:
	gcc -c -I$(path) stillOnTheRoadQ2.c -o stillOnTheRoadQ2.o 

EDLstillOnTheRoadQ2:
	gcc  stillOnTheRoadQ2.o  -o stillOnTheRoadQ2 -L$(path) -pthread -lroad -lallegro -lallegro_primitives 

compstillOnTheRoadQ2.2:
	gcc -c -I$(path) stillOnTheRoadQ2.2.c -o stillOnTheRoadQ2.2.o 

EDLstillOnTheRoadQ2.2:
	gcc  stillOnTheRoadQ2.2.o  -o stillOnTheRoadQ2.2 -L$(path) -pthread -lroad -lallegro -lallegro_primitives 

compstillOnTheRoadQ3:
	gcc -c -I$(path) stillOnTheRoadQ3.c -o stillOnTheRoadQ3.o 

EDLstillOnTheRoadQ3:
	gcc  stillOnTheRoadQ3.o  -o stillOnTheRoadQ3 -L$(path) -pthread -lroad -lallegro -lallegro_primitives 

compstillOnTheRoadQ4:
	gcc -c -I$(path) stillOnTheRoadQ4.c -o stillOnTheRoadQ4.o 

EDLstillOnTheRoadQ4:
	gcc  stillOnTheRoadQ4.o  -o stillOnTheRoadQ4 -L$(path) -pthread -lroad -lallegro -lallegro_primitives 


