compforkWait: forkWait.c
	gcc -c forkWait.c -o forkWait.o

EDLforkWait: forkWait.o
	gcc forkWait.o -o forkWait

AllforkWait: forkWait.c 
	gcc forkWait.c -o forkWait

compforkGlobales: forkGlobales.c
	gcc -c forkGlobales.c -o forkGlobales.o

EDLforkGlobales: forkGlobales.o
	gcc forkGlobales.o -o forkGlobales

AllforkGlobales: forkGlobales.c 
	gcc forkGlobales.c -o forkGlobales

compforkShared: forkShared.c
	gcc -c forkShared.c -o forkShared.o

EDLforkShared: forkShared.o
	gcc forkShared.o -o forkShared

AllforkShared: forkShared.c 
	gcc forkShared.c -o forkShared

compforkShared2: forkShared2.c
	gcc -c forkShared2.c -o forkShared2.o

EDLforkShared2: forkShared2.o
	gcc forkShared2.o -o forkShared2

AllforkShared2: forkShared2.c 
	gcc forkShared2.c -o forkShared2

compbonus: bonus.c
	gcc -c bonus.c -o bonus.o

EDLbonus: bonus.o
	gcc bonus.o -o bonus

Allbonus: bonus.c 
	gcc bonus.c -o bonus